version: '3'
services:

  bot:
    container_name: calendeye-bot
    build:
      context: ./bot
      dockerfile: Dockerfile
    env_file:
      - ./bot/.env
    ports:
      - 5000:80
    depends_on:
      db:
        condition: service_healthy

  web:
    container_name: calendeye-web
    build:
      context: ./web
      dockerfile: Dockerfile
    env_file:
      - ./web/.env
    ports:
      - 5173:80

  db:
    container_name: calendeye-db
    image: postgres:15
    env_file:
      - ./bot/.env
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 2s
      timeout: 5s
      retries: 5

volumes:
  dbdata: null
