version: '3'
services:

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    env_file:
      - ./bot/.env
    ports:
      - 5000:80

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    env_file:
      - ./web/.env
    ports:
      - 5173:80
