name: bot-ci
on: 
  push:
    paths:
      - "bot/**"
jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup
        uses: actions/setup-go@v5
      - name: static check
        run: cd bot && make ci-lint

  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup
        uses: actions/setup-go@v5
      - name: static check
        run: cd bot && make build
